[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
nom = "7.1.3"

[dev-dependencies]
indoc = "2.0.5"
